[package]
name = "axum_simple_middleware"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
hyper = "1.6.0"
serde = "1.0.217"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full", "macros", "rt-multi-thread"] }
tower = "0.5.2"
